// Regression tests for Bug 1 from the real-device verification report:
// "Damage images missing in final listing preview" -- damage photos
// rendered fine on the Step4 damage-photo grid (HEIF previews work there,
// see `sell_damage_heic_preview_test.dart`), but tapping through to the
// final "Preview Listing" step's damage-photos gallery (reached via
// `buildCarListingSpecsGrid()` -> "Title Status" row ->
// `listingDamagePreviewEntries()` -> `ListingPreviewMediaGridPage` ->
// `ListingPreviewMediaViewerPage`, see `car_listing_specs_grid_build.dart`
// / `car_listing_specs_grid_damage.dart`) showed a broken-image
// placeholder instead.
//
// Root cause (confirmed by reading `listing_preview_media_grid_page.dart`
// and `listing_preview_media_viewer_page.dart` -- the actual widgets these
// two production call sites push): `_buildImageTile()` /`_buildImage()`
// called `ListingImageMedia.localFile(item)` directly, handing Flutter's
// Skia-based `Image.file`/`Image.memory` decoder the RAW HEIC/HEIF source
// path for a not-yet-uploaded photo. Skia cannot decode HEIC/HEIF at all,
// so the tile/viewer always rendered a broken-image placeholder even
// though the JPEG `preview_source` (generated by `HeicPreviewConverter`,
// the same one already used correctly by the Step4 grids and the main
// preview carousel in `sell_step4_preview_review.dart`) was sitting right
// on the item.
//
// Fix: both call sites now use the EXISTING
// `ListingImageMedia.previewLocalFile(item)`, which transparently falls
// back to `localFile()` unchanged for JPEG/PNG originals or once no
// preview exists -- so this is purely additive for the "HEIC/HEIF preview
// is ready" case. Upload/submission code (`sell_listing_media_upload.dart`)
// is untouched -- it never reads this widget and keeps using
// `source()`/`localFile()` exclusively (already proven by
// `sell_damage_heic_preview_test.dart`).
//
// `ListingPreviewWidget` (`sell_step4_preview_listing.dart`) is confirmed
// dead code (only its own constructor references it; never instantiated
// anywhere in the app or tests) and is intentionally left untouched/out of
// scope.
import 'dart:io';
import 'dart:typed_data';

import 'package:car_listing_app/pages/listing_image_gallery_page.dart';
import 'package:car_listing_app/shared/listings/listing_image_media.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart' as p;

String _stripDartComments(String source) {
  final buffer = StringBuffer();
  for (final line in source.split('\n')) {
    final idx = line.indexOf('//');
    buffer.writeln(idx == -1 ? line : line.substring(0, idx));
  }
  return buffer.toString();
}


// Smallest possible valid 1x1 PNG (opaque black pixel) -- enough for
// Flutter's real (non-mocked) image codec to successfully decode in a
// widget test, unlike arbitrary garbage bytes.
final Uint8List _validPngBytes = Uint8List.fromList(<int>[
  0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D,
  0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
  0x08, 0x06, 0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4, 0x89, 0x00, 0x00, 0x00,
  0x0D, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9C, 0x63, 0x64, 0x60, 0x60, 0x60,
  0x00, 0x00, 0x00, 0x05, 0x00, 0x01, 0x5A, 0x8B, 0x9C, 0x99, 0x00, 0x00,
  0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
]);

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('static wiring: final-preview gallery widgets use previewLocalFile', () {
    late String gridContent;
    late String viewerContent;

    setUpAll(() {
      gridContent = _stripDartComments(
        File(
          p.join('lib', 'pages', 'listing_preview_media_grid_page.dart'),
        ).readAsStringSync(),
      );
      viewerContent = _stripDartComments(
        File(
          p.join('lib', 'pages', 'listing_preview_media_viewer_page.dart'),
        ).readAsStringSync(),
      );
    });

    test(
      'ListingPreviewMediaGridPage._buildImageTile resolves via '
      'previewLocalFile(), never the raw localFile()',
      () {
        expect(
          gridContent.contains('ListingImageMedia.previewLocalFile(item)'),
          isTrue,
        );
        expect(
          gridContent.contains('ListingImageMedia.localFile(item)'),
          isFalse,
          reason: 'must not fall back to raw localFile() directly -- '
              'previewLocalFile() already does that internally when no '
              'preview exists',
        );
      },
    );

    test(
      'ListingPreviewMediaViewerPage._buildImage resolves via '
      'previewLocalFile(), never the raw localFile()',
      () {
        expect(
          viewerContent.contains('ListingImageMedia.previewLocalFile(item)'),
          isTrue,
        );
        expect(
          viewerContent.contains('ListingImageMedia.localFile(item)'),
          isFalse,
        );
      },
    );
  });

  group('end-to-end widget behavior: HEIC damage photo with a ready JPEG '
      'preview renders in the real final-preview gallery widgets', () {
    late Directory tempDir;
    late String heicPath;
    late String jpegPreviewPath;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('final_preview_damage_');
      // A HEIC file with garbage bytes -- Skia cannot decode this (same as
      // a real, not-yet-uploaded HEIC photo straight from the camera would
      // fail to decode via Image.file/Image.memory).
      heicPath = p.join(tempDir.path, 'damage_orig.heic');
      File(heicPath).writeAsBytesSync(List<int>.filled(64, 0xAB));
      // The JPEG preview HeicPreviewConverter would have generated --
      // real, decodable image bytes.
      jpegPreviewPath = p.join(tempDir.path, 'damage_preview.jpg');
      File(jpegPreviewPath).writeAsBytesSync(_validPngBytes);
    });

    tearDown(() {
      try {
        tempDir.deleteSync(recursive: true);
      } catch (_) {
        // Best-effort cleanup; a leftover temp dir must never fail a test.
      }
    });

    Future<void> pumpGrid(WidgetTester tester, dynamic damageItem) async {
      await tester.pumpWidget(
        MaterialApp(
          home: ListingPreviewMediaGridPage(
            imageFilesOrUrls: [damageItem],
            appBarTitle: 'Damage photos',
          ),
        ),
      );
      await tester.pumpAndSettle();
    }

    testWidgets(
      'grid: a HEIC damage item WITH a ready preview_source renders the '
      'JPEG preview, not a broken-image placeholder',
      (tester) async {
        final damageItem = ListingImageMedia.map(
          XFile(heicPath),
          previewSource: jpegPreviewPath,
        );

        await pumpGrid(tester, damageItem);

        expect(
          find.byIcon(Icons.broken_image),
          findsNothing,
          reason: 'the grid must resolve to the decodable JPEG preview '
              '(previewLocalFile), not attempt to decode the raw HEIC '
              'source directly',
        );
      },
    );

    test(
      'control case -- with NO preview_source, previewLocalFile() '
      'resolves to the RAW (undecodable) HEIC path, not the fixed-up '
      'JPEG one (proves the positive tests above are truly exercising the '
      'preview_source substitution, not a coincidence)',
      () {
        final damageItemNoPreview = ListingImageMedia.map(XFile(heicPath));
        expect(
          ListingImageMedia.previewLocalFile(damageItemNoPreview)?.path,
          heicPath,
        );
        final damageItemWithPreview = ListingImageMedia.map(
          XFile(heicPath),
          previewSource: jpegPreviewPath,
        );
        expect(
          ListingImageMedia.previewLocalFile(damageItemWithPreview)?.path,
          jpegPreviewPath,
        );
      },
    );

    testWidgets(
      'full-screen viewer (pushed by tapping the grid tile): a HEIC '
      'damage item with a ready preview_source renders the JPEG preview, '
      'not a broken-image placeholder',
      (tester) async {
        final damageItem = ListingImageMedia.map(
          XFile(heicPath),
          previewSource: jpegPreviewPath,
        );

        await tester.pumpWidget(
          MaterialApp(
            home: ListingPreviewMediaViewerPage(
              imageFilesOrUrls: [damageItem],
            ),
          ),
        );
        await tester.pumpAndSettle();

        expect(find.byIcon(Icons.broken_image), findsNothing);
      },
    );

    testWidgets(
      'tapping a damage tile in the grid opens the viewer, which shows '
      'the SAME resolved preview (no re-decode-from-raw-HEIC regression '
      'across the grid -> viewer navigation)',
      (tester) async {
        final damageItem = ListingImageMedia.map(
          XFile(heicPath),
          previewSource: jpegPreviewPath,
        );

        await pumpGrid(tester, damageItem);
        expect(find.byIcon(Icons.broken_image), findsNothing);

        await tester.tap(find.byType(InkWell).first);
        await tester.pumpAndSettle();

        expect(
          find.byType(ListingPreviewMediaViewerPage),
          findsOneWidget,
          reason: 'tapping the tile must open the full-screen viewer',
        );
        expect(find.byIcon(Icons.broken_image), findsNothing);
      },
    );
  });
}
