workflows:
  ios_adhoc_unsigned:
    name: iOS Ad-hoc (unsigned IPA for Sideloadly)
    environment:
      flutter: stable
      xcode: latest
      vars:
        # IMPORTANT: Do NOT include /api in API_BASE. The app adds /api itself.
        # Set to your PC LAN IP (run ipconfig); override in Codemagic UI if different.
        API_BASE: "http://192.168.1.7:5003"
    scripts:
      - name: Flutter pub get
        script: |
          flutter --version
          flutter pub get
      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign --dart-define=API_BASE=${API_BASE}
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos
          rm -rf Payload
          mkdir -p Payload
          # Runner.app is the default Flutter product name
          mv Runner.app Payload/
          zip -qry app-unsigned.ipa Payload
    artifacts:
      - build/ios/iphoneos/app-unsigned.ipa
      - build/ios/iphoneos/Payload/Runner.app

  android_release_unsigned:
    name: Android APK (release, unsigned)
    environment:
      flutter: stable
      vars:
        # IMPORTANT: Do NOT include /api in API_BASE. The app adds /api itself.
        # Set to your PC LAN IP (run ipconfig); override in Codemagic UI if different.
        API_BASE: "http://192.168.1.7:5003"
    scripts:
      - name: Flutter pub get
        script: |
          flutter --version
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --dart-define=API_BASE=${API_BASE}
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  android-dev-debug:
    name: Android (dev) - Debug
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      vars:
        FLAVOR: dev
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Analyze
        script: flutter analyze
      - name: Tests
        script: flutter test --no-pub
      - name: Build APK (debug)
        script: flutter build apk --debug --no-pub --flavor "$FLAVOR"
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  android-prod-release:
    name: Android (prod) - Release APK/AAB
    max_build_duration: 90
    instance_type: linux_x2
    environment:
      flutter: stable
      vars:
        FLAVOR: prod
      # Configure these in Codemagic UI (Environment variables / Secure):
      # - CM_KEYSTORE (base64 of your .jks)
      # - CM_KEYSTORE_PASSWORD
      # - CM_KEY_ALIAS
      # - CM_KEY_PASSWORD
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Write Android signing files (optional)
        script: |
          if [ -n "$CM_KEYSTORE" ]; then
            echo "Signing config detected; writing keystore + signing.properties"
            KEYSTORE_PATH="$CM_BUILD_DIR/android/upload-keystore.jks"
            echo "$CM_KEYSTORE" | base64 --decode > "$KEYSTORE_PATH"
            # rootProject in app/build.gradle.kts is android/, so signing.properties goes there
            printf 'STORE_FILE=%s\nSTORE_PASSWORD=%s\nKEY_ALIAS=%s\nKEY_PASSWORD=%s\n' \
              "$KEYSTORE_PATH" "$CM_KEYSTORE_PASSWORD" "$CM_KEY_ALIAS" "$CM_KEY_PASSWORD" \
              > "$CM_BUILD_DIR/android/signing.properties"
          else
            echo "No signing env vars set; building a release signed with debug key (not store-ready)."
          fi
      - name: Analyze
        script: flutter analyze
      - name: Tests
        script: flutter test --no-pub
      - name: Build APK (release)
        script: flutter build apk --release --no-pub --flavor "$FLAVOR"
      - name: Build App Bundle (release)
        script: flutter build appbundle --release --no-pub --flavor "$FLAVOR"
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/*/*.aab

  ios-sideloadly-unsigned:
    name: iOS (Unsigned IPA for Sideloadly)
    max_build_duration: 90
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # For iPhone on same Wi‑Fi use your PC LAN IP (run ipconfig).
        # For real device over internet or ATS: use HTTPS (e.g. Cloudflare tunnel).
        # Override in Codemagic UI (Environment variables) if needed.
        # IMPORTANT: Do NOT include /api in API_BASE. The app adds /api itself.
        API_BASE: "http://192.168.1.7:5003"
        FORCE_SKIP_BLUR: "false"
    scripts:
      - name: Flutter version
        script: flutter --version
      - name: Clean + pub get
        script: |
          flutter clean
          flutter pub get
      - name: Analyze + tests
        script: |
          flutter analyze
          flutter test
      - name: Build iOS app (no codesign)
        script: |
          flutter build ios --release --no-codesign \
            --dart-define=API_BASE="$API_BASE" \
            --dart-define=FORCE_SKIP_BLUR="$FORCE_SKIP_BLUR"
      - name: Package unsigned IPA for Sideloadly
        script: |
          set -e
          DEST_DIR="$CM_BUILD_DIR/build/ios/ipa"
          mkdir -p "$DEST_DIR"
          APP_SRC="$CM_BUILD_DIR/build/ios/iphoneos/Runner.app"
          if [ ! -d "$APP_SRC" ]; then
            echo "Runner.app not found at $APP_SRC"
            echo "Listing build/ios:"
            ls -la "$CM_BUILD_DIR/build/ios" || true
            exit 1
          fi
          TMP_DIR=$(mktemp -d)
          mkdir -p "$TMP_DIR/Payload"
          cp -R "$APP_SRC" "$TMP_DIR/Payload/Runner.app"
          (cd "$TMP_DIR" && zip -qry Runner-unsigned.ipa Payload)
          mv "$TMP_DIR/Runner-unsigned.ipa" "$DEST_DIR/Runner-unsigned.ipa"
          echo "Created unsigned IPA at $DEST_DIR/Runner-unsigned.ipa"
    artifacts:
      - build/ios/ipa/*.ipa
    cache:
      cache_paths:
        - "$FLUTTER_ROOT/.pub-cache"
        - "~/.pub-cache"
        - "build/"