workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    cache:
      cache_paths: []
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'revert-exact-6b82de9'
          include: true
          source: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.carzo.app
        # Development API endpoint for sideload builds (no trailing slash)
        # Updated to match your actual server IP
        API_BASE: http://192.168.1.8:5000
    scripts:
      - name: Print commit used for this build
        script: |
          echo "Building commit: $(git rev-parse HEAD)"
          git log -1 --pretty=oneline
      - name: Force clean Flutter and iOS workspace
        script: |
          set -e
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          rm -rf "$HOME/Library/Developer/Xcode/DerivedData" || true
          flutter pub get
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Bootstrap iOS build settings
        script: |
          flutter pub get
          flutter precache --ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          dart analyze --no-fatal-warnings --no-fatal-infos || true
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build iOS IPA (release, unsigned for Sideloadly)
        script: |
          # Disable App Transport Security restrictions for sideload testing
          /usr/libexec/PlistBuddy -c 'Add :NSAppTransportSecurity:NSAllowsArbitraryLoads bool YES' ios/Runner/Info.plist || true
          # Remove background modes that may require entitlements on unsandboxed builds
          /usr/libexec/PlistBuddy -c 'Delete :UIBackgroundModes' ios/Runner/Info.plist || true
          # Build with defines to disable Firebase/Push on sideload and set API base if provided
          DEFINE_API_BASE=${API_BASE:-}
          GIT_SHA=$(git rev-parse --short=8 HEAD)
          if [ -n "$DEFINE_API_BASE" ]; then
            echo "Using API_BASE=$DEFINE_API_BASE"
            flutter build ipa --release --no-codesign --dart-define=SIDELOAD_BUILD=true --dart-define=BUILD_COMMIT_SHA=$GIT_SHA --dart-define=API_BASE=$DEFINE_API_BASE || true
          else
            flutter build ipa --release --no-codesign --dart-define=SIDELOAD_BUILD=true --dart-define=BUILD_COMMIT_SHA=$GIT_SHA || true
          fi
      - name: Package unsigned IPA from xcarchive
        script: |
          set -e
          ARCHIVE_PATH="$CM_BUILD_DIR/build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app"
          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "Runner.app not found at $ARCHIVE_PATH"
            echo "Available files in archive directory:"
            ls -la "$CM_BUILD_DIR/build/ios/archive" || true
            exit 0
          fi
          # Remove app extensions that may require missing entitlements in sideload
          rm -rf "$ARCHIVE_PATH/PlugIns" || true
          rm -rf "$ARCHIVE_PATH/Watch" || true
          TMP_DIR=$(mktemp -d)
          mkdir -p "$TMP_DIR/Payload"
          cp -R "$ARCHIVE_PATH" "$TMP_DIR/Payload/Runner.app"
          (cd "$TMP_DIR" && zip -qry Runner-unsigned.ipa Payload)
          mkdir -p "$CM_BUILD_DIR/build/ios/ipa"
          mv "$TMP_DIR/Runner-unsigned.ipa" "$CM_BUILD_DIR/build/ios/ipa/Runner-unsigned.ipa"
          echo "Created unsigned IPA at build/ios/ipa/Runner-unsigned.ipa"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false