workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.carzo.app
      groups:
        - app_store_connect
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Bootstrap iOS build settings
        script: |
          flutter pub get
          flutter precache --ios
      - name: Automatic code signing (development)
        script: |
          keychain add --name ios-signing --password "$KEYCHAIN_PASSWORD"
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --api-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --create
          keychain use ios-signing
          xcode-project use-profiles
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          dart analyze --no-fatal-warnings --no-fatal-infos || true
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build iOS IPA (release, development-signed)
        script: |
          flutter build ipa --release || true
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
