workflows:
  ios-car-listing-app:
    name: Car Listing App iOS
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars: {}
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Fetch Ad Hoc signing files
        script: |
          app-store-connect fetch-signing-files "com.carzo.app" --type IOS_ADHOC --create
      - name: Use signing profiles
        script: |
          xcode-project use-profiles
      - name: Install Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build iOS app
        script: |
          flutter build ios --release
      - name: Build iOS IPA (Ad Hoc)
        script: |
          flutter build ipa --export-options-plist ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
