workflows:
  ios-car-listing-app:
    name: Car Listing App iOS
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Override per-build to your reachable backend from device
        API_BASE: http://192.168.1.13:5000
    scripts:
      - name: Print commit used for this build
        script: |
          echo "Building commit: $(git rev-parse HEAD)"
          git log -1 --pretty=oneline
      - name: Force clean Flutter and iOS workspace
        script: |
          set -e
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          rm -rf "$HOME/Library/Developer/Xcode/DerivedData" || true
          flutter pub get
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Fetch Ad Hoc signing files
        script: |
          app-store-connect fetch-signing-files "com.carzo.app" --type IOS_ADHOC --create
      - name: Use signing profiles
        script: |
          xcode-project use-profiles
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Bootstrap iOS build settings
        script: |
          flutter precache --ios
          # Ensure Generated.xcconfig exists by invoking a config-only iOS build
          flutter build ios --release --no-codesign
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build iOS app
        script: |
          # Allow ATS for sideload/dev
          /usr/libexec/PlistBuddy -c 'Add :NSAppTransportSecurity:NSAllowsArbitraryLoads bool YES' ios/Runner/Info.plist || true
          # Pass API base and commit SHA for verification
          GIT_SHA=$(git rev-parse --short=8 HEAD)
          flutter build ios --release \
            --dart-define=BUILD_COMMIT_SHA=$GIT_SHA \
            --dart-define=API_BASE=${API_BASE:-}
      - name: Build iOS IPA (Ad Hoc)
        script: |
          GIT_SHA=$(git rev-parse --short=8 HEAD)
          flutter build ipa --export-options-plist ios/ExportOptions.plist \
            --dart-define=BUILD_COMMIT_SHA=$GIT_SHA \
            --dart-define=API_BASE=${API_BASE:-}
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
