import 'dart:convert';

import 'package:shared_preferences/shared_preferences.dart';

import '../debug/app_log.dart';

/// F-11: durable record of an outgoing chat REST send that failed with a
/// retryable (transient network/transport) error, so it can be retried
/// safely later — after connectivity returns, the chat is reopened, or the
/// app restarts — without generating a new logical send and therefore
/// without risking a duplicate `Message` row (the retry reuses the exact
/// same `idempotencyKey` already generated by `OutgoingChatSendService`;
/// see BE-18 / kk/idempotency.py for the server-side replay contract this
/// relies on).
///
/// Only non-sensitive send metadata is stored: no auth/refresh tokens, no
/// `Authorization` header, nothing beyond what the send itself already
/// needed (conversation id, message content/caption, the local media file
/// paths the user already picked, and the idempotency key). Media file
/// *paths* are stored, not copies of the files themselves — F-11 explicitly
/// scopes out duplicating media storage.
class ChatPendingSendRecord {
  ChatPendingSendRecord({
    required this.id,
    required this.conversationId,
    required this.kind,
    required this.idempotencyKey,
    required this.createdAt,
    required this.attempts,
    this.content,
    this.receiverId,
    this.replyToMessageId,
    this.replyToPreviewJson,
    this.listingPreview,
    this.filePaths = const <String>[],
    this.lastAttemptAt,
    this.lastError,
  });

  /// Stable id for this logical send (the temp/pending message id).
  final String id;
  final String conversationId;

  /// One of 'text' | 'mediaGroup' | 'audio' — mirrors [OutgoingChatSendKind]
  /// without importing it here, to keep this a plain persistence file.
  final String kind;
  final String idempotencyKey;
  final String? content;
  final String? receiverId;
  final String? replyToMessageId;
  final Map<String, dynamic>? replyToPreviewJson;
  final Map<String, dynamic>? listingPreview;
  final List<String> filePaths;
  final int createdAt;
  final int attempts;
  final int? lastAttemptAt;
  final String? lastError;

  ChatPendingSendRecord copyWith({
    int? attempts,
    int? lastAttemptAt,
    String? lastError,
  }) {
    return ChatPendingSendRecord(
      id: id,
      conversationId: conversationId,
      kind: kind,
      idempotencyKey: idempotencyKey,
      createdAt: createdAt,
      content: content,
      receiverId: receiverId,
      replyToMessageId: replyToMessageId,
      replyToPreviewJson: replyToPreviewJson,
      listingPreview: listingPreview,
      filePaths: filePaths,
      attempts: attempts ?? this.attempts,
      lastAttemptAt: lastAttemptAt ?? this.lastAttemptAt,
      lastError: lastError ?? this.lastError,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'conversationId': conversationId,
        'kind': kind,
        'idempotencyKey': idempotencyKey,
        if (content != null) 'content': content,
        if (receiverId != null) 'receiverId': receiverId,
        if (replyToMessageId != null) 'replyToMessageId': replyToMessageId,
        if (replyToPreviewJson != null)
          'replyToPreviewJson': replyToPreviewJson,
        if (listingPreview != null) 'listingPreview': listingPreview,
        'filePaths': filePaths,
        'createdAt': createdAt,
        'attempts': attempts,
        if (lastAttemptAt != null) 'lastAttemptAt': lastAttemptAt,
        if (lastError != null) 'lastError': lastError,
      };

  static ChatPendingSendRecord? fromJson(dynamic raw) {
    if (raw is! Map) return null;
    try {
      final map = Map<String, dynamic>.from(raw.cast<String, dynamic>());
      final id = (map['id'] ?? '').toString().trim();
      final conversationId = (map['conversationId'] ?? '').toString().trim();
      final kind = (map['kind'] ?? '').toString().trim();
      final idempotencyKey = (map['idempotencyKey'] ?? '').toString().trim();
      if (id.isEmpty ||
          conversationId.isEmpty ||
          kind.isEmpty ||
          idempotencyKey.isEmpty) {
        return null;
      }
      final rawFiles = map['filePaths'];
      final filePaths = rawFiles is List
          ? rawFiles
              .map((e) => e.toString())
              .where((s) => s.isNotEmpty)
              .toList()
          : <String>[];
      final rawReply = map['replyToPreviewJson'];
      final rawListing = map['listingPreview'];
      return ChatPendingSendRecord(
        id: id,
        conversationId: conversationId,
        kind: kind,
        idempotencyKey: idempotencyKey,
        content: map['content']?.toString(),
        receiverId: map['receiverId']?.toString(),
        replyToMessageId: map['replyToMessageId']?.toString(),
        replyToPreviewJson: rawReply is Map
            ? Map<String, dynamic>.from(rawReply.cast<String, dynamic>())
            : null,
        listingPreview: rawListing is Map
            ? Map<String, dynamic>.from(rawListing.cast<String, dynamic>())
            : null,
        filePaths: filePaths,
        createdAt: (map['createdAt'] as num?)?.toInt() ??
            DateTime.now().millisecondsSinceEpoch,
        attempts: (map['attempts'] as num?)?.toInt() ?? 0,
        lastAttemptAt: (map['lastAttemptAt'] as num?)?.toInt(),
        lastError: map['lastError']?.toString(),
      );
    } catch (e, st) {
      logNonFatal(e, st);
      return null;
    }
  }
}

/// Durable storage for [ChatPendingSendRecord]s (F-11).
///
/// Backed by a single small JSON-list `SharedPreferences` entry, mirroring
/// the existing `SellPendingMediaPrefs` convention used for the (unrelated,
/// already-resilient) sell-listing-media resume path.
class ChatPendingSendPrefs {
  ChatPendingSendPrefs._();

  static const String prefsKey = 'chat_pending_sends_v1';

  static Future<List<ChatPendingSendRecord>> loadAll() async {
    try {
      final sp = await SharedPreferences.getInstance();
      final raw = sp.getString(prefsKey);
      if (raw == null || raw.trim().isEmpty) {
        return const <ChatPendingSendRecord>[];
      }
      final decoded = json.decode(raw);
      if (decoded is! List) return const <ChatPendingSendRecord>[];
      final out = <ChatPendingSendRecord>[];
      for (final item in decoded) {
        final rec = ChatPendingSendRecord.fromJson(item);
        if (rec != null) out.add(rec);
      }
      return out;
    } catch (e, st) {
      logNonFatal(e, st);
      return const <ChatPendingSendRecord>[];
    }
  }

  static Future<List<ChatPendingSendRecord>> loadForConversation(
    String conversationId,
  ) async {
    final all = await loadAll();
    return all.where((r) => r.conversationId == conversationId).toList();
  }

  static Future<void> _saveAll(List<ChatPendingSendRecord> records) async {
    final sp = await SharedPreferences.getInstance();
    if (records.isEmpty) {
      await sp.remove(prefsKey);
      return;
    }
    final encoded = json.encode(records.map((r) => r.toJson()).toList());
    await sp.setString(prefsKey, encoded);
  }

  /// Insert or update a pending record (matched by [ChatPendingSendRecord.id]).
  static Future<void> upsert(ChatPendingSendRecord record) async {
    try {
      // loadAll() may return the shared immutable empty list — copy into a
      // growable list before mutating it below.
      final all = List<ChatPendingSendRecord>.from(await loadAll());
      final idx = all.indexWhere((r) => r.id == record.id);
      if (idx == -1) {
        all.add(record);
      } else {
        all[idx] = record;
      }
      await _saveAll(all);
    } catch (e, st) {
      logNonFatal(e, st);
    }
  }

  /// Remove a pending record. Idempotent — safe to call more than once or
  /// for an id that was never persisted (e.g. a send that never failed).
  static Future<void> remove(String id) async {
    try {
      final all = await loadAll();
      final next = all.where((r) => r.id != id).toList();
      if (next.length == all.length) return;
      await _saveAll(next);
    } catch (e, st) {
      logNonFatal(e, st);
    }
  }
}
